
package ip5;

import java.io.IOException;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @CYRUS LOMIBAO
 */
public class SalesTracker5 extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public SalesTracker5() {
        initComponents();
        idError.setVisible(false);
        fNameError.setVisible(false);
        lNameError.setVisible(false);
        suppliesError.setVisible(false);
        booksError.setVisible(false);
        paperError.setVisible(false);
        successLabel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastNameInput = new javax.swing.JTextField();
        quitButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        salesIdInput = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        suppliesInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        booksInput = new javax.swing.JTextField();
        paperInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        districtComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phoneRadioButton = new javax.swing.JRadioButton();
        emailRadioButton = new javax.swing.JRadioButton();
        meetingRadioButton = new javax.swing.JRadioButton();
        idError = new javax.swing.JLabel();
        fNameError = new javax.swing.JLabel();
        lNameError = new javax.swing.JLabel();
        suppliesError = new javax.swing.JLabel();
        booksError = new javax.swing.JLabel();
        paperError = new javax.swing.JLabel();
        successLabel = new javax.swing.JLabel();
        displayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayOutput = new javax.swing.JTextArea();
        evaluateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        submitButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(51, 51, 51));
        submitButton.setText("ENTER");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        quitButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        quitButton.setForeground(new java.awt.Color(51, 51, 51));
        quitButton.setText("QUIT");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Sales ID:");

        statusLabel.setForeground(new java.awt.Color(0, 102, 51));

        jLabel4.setText("Supplies:");

        jLabel5.setText(" Books:");

        jLabel6.setText("Paper:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("SalesTracker (version 1.2)");

        districtComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORTH", "SOUTH", "EAST", "WEST" }));
        districtComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Sales:");

        jLabel9.setText("District:");

        jLabel10.setText("Contact Method:");

        buttonGroup1.add(phoneRadioButton);
        phoneRadioButton.setText("PHONE");
        phoneRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(emailRadioButton);
        emailRadioButton.setText("EMAIL");

        buttonGroup1.add(meetingRadioButton);
        meetingRadioButton.setText("MEETING");

        idError.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        idError.setForeground(new java.awt.Color(255, 0, 0));
        idError.setText("* Sales ID number required");

        fNameError.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        fNameError.setForeground(new java.awt.Color(255, 0, 0));
        fNameError.setText("* First name required");

        lNameError.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lNameError.setForeground(new java.awt.Color(255, 0, 0));
        lNameError.setText("* Last name required");

        suppliesError.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        suppliesError.setForeground(new java.awt.Color(255, 0, 0));
        suppliesError.setText("* Dollar amount required");

        booksError.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        booksError.setForeground(new java.awt.Color(255, 0, 0));
        booksError.setText("* Dollar amount required");

        paperError.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        paperError.setForeground(new java.awt.Color(255, 0, 0));
        paperError.setText("* Dollar amount required");

        successLabel.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        successLabel.setForeground(new java.awt.Color(51, 51, 51));
        successLabel.setText("Successfully Saved!");

        displayButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        displayButton.setForeground(new java.awt.Color(51, 51, 51));
        displayButton.setText("DISPLAY");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        displayOutput.setEditable(false);
        displayOutput.setColumns(20);
        displayOutput.setRows(5);
        jScrollPane1.setViewportView(displayOutput);

        evaluateButton.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        evaluateButton.setForeground(new java.awt.Color(51, 51, 51));
        evaluateButton.setText("EVALUATE");
        evaluateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paperInput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(booksInput, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(suppliesInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(suppliesError, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(booksError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paperError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(districtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salesIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idError, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(phoneRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(meetingRadioButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(69, 69, 69)
                .addComponent(statusLabel))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(evaluateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(displayButton)
                                .addGap(10, 10, 10)
                                .addComponent(quitButton)))))
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(statusLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(salesIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(firstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(suppliesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suppliesError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(booksInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booksError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paperInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(paperError))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(districtComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(phoneRadioButton)
                    .addComponent(emailRadioButton)
                    .addComponent(meetingRadioButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(quitButton)
                    .addComponent(evaluateButton)
                    .addComponent(displayButton))
                .addGap(18, 18, 18)
                .addComponent(successLabel)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed

        boolean allDataRecieved = true;
        SalesPerson p = new SalesPerson();

        String empId = salesIdInput.getText();
        try {
            int salesId = Integer.parseInt(empId);
            if (salesId <= 0) {
                idError.setVisible(true);
                allDataRecieved = false;
            } else {
                p.setSalesId(salesId);
                idError.setVisible(false);
            }
        } catch (NumberFormatException e) {
            idError.setVisible(true);
            allDataRecieved = false;
        }

        String firstName = firstNameInput.getText();

        if (firstName.trim().length() == 0) {
            fNameError.setVisible(true);
            allDataRecieved = false;
        } else {
            firstNameInput.setText(firstName.trim());
            p.setFirstName(firstName.trim());
            fNameError.setVisible(false);

        }

        String lastName = lastNameInput.getText();

        if (lastName.trim().length() == 0) {
            lNameError.setVisible(true);
            allDataRecieved = false;
        } else {
            lastNameInput.setText(lastName);
            p.setLastName(lastName.trim());
            lNameError.setVisible(false);
        }

        String totalSupplies = suppliesInput.getText();
        try {
            double supplies = Double.parseDouble(totalSupplies);
            if (supplies <= 0) {
                p.setSupplies(0.00);
            } else {
                p.setSupplies(supplies);
                suppliesError.setVisible(false);
            }
        } catch (NumberFormatException e) {
            suppliesError.setVisible(true);
            allDataRecieved = false;
        }

        String totalBooks = booksInput.getText();
        try {
            double books = Double.parseDouble(totalBooks);
            if (books <= 0) {
                p.setBooks(0.00);
            } else {
                p.setBooks(books);
                booksError.setVisible(false);
            }
        } catch (NumberFormatException e) {
            booksError.setVisible(true);
            allDataRecieved = false;
        }

        String totalPaper = paperInput.getText();
        try {
            double paper = Double.parseDouble(totalPaper);
            if (paper <= 0) {
                p.setPaper(0.00);
            } else {
                p.setPaper(paper);
                paperError.setVisible(false);
            }
        } catch (NumberFormatException e) {
            paperError.setVisible(true);
            allDataRecieved = false;
        }

        // Combo box action
        if (districtComboBox != null) {
            String district = (districtComboBox.getSelectedItem().toString());
            p.setDistrict(district);
        }
        // Radio Button selection
        if (buttonGroup1.getSelection() != null) {
            String contact = (buttonGroup1.getSelection().toString());
            if (phoneRadioButton.isSelected()) {
                p.setContact("PHONE");
            } else if (emailRadioButton.isSelected()) {
                p.setContact("EMAIL");
            } else if (meetingRadioButton.isSelected()) {
                p.setContact("MEETING");
            }
        }
        p.calculateTotals();
        if (allDataRecieved) {
            try {
                SalesPersonStorage pfs = new SalesPersonStorage();
                pfs.writePerson(p);

                successLabel.setVisible(true);
                salesIdInput.setText("");
                firstNameInput.setText("");
                lastNameInput.setText("");
                suppliesInput.setText("");
                booksInput.setText("");
                paperInput.setText("");

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error writing to file");
                Logger.getLogger(SalesTracker5.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void phoneRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneRadioButtonActionPerformed

    }//GEN-LAST:event_phoneRadioButtonActionPerformed

    private void districtComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtComboBoxActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        displayOutput.setText("");
        SalesPersonReader reader = new SalesPersonReader();
        try {
            Collection<SalesPerson> people = reader.readPeople("stars.txt");
            people.stream().map((SalesPerson p) -> {
                displayOutput.append(p.toString());
                return p;
            }).forEachOrdered((SalesPerson _item) -> {
                displayOutput.append("\n");
            });

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Unable to open file");
            Logger.getLogger(SalesTracker5.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_displayButtonActionPerformed

    private void evaluateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluateButtonActionPerformed
        displayOutput.setText("");
        SalesPersonReader reader = new SalesPersonReader();
        try {
            Collection<SalesPerson> people = reader.readPeople("salesperson.txt");
            StarSalesPerson ssp = new StarSalesPerson();         
            displayOutput.append(ssp.star(people).toString());
            displayOutput.append("\n");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Unable to open file");
            Logger.getLogger(SalesTracker5.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_evaluateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesTracker5.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
      

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
			new SalesTracker5().setVisible(true);
		});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booksError;
    private javax.swing.JTextField booksInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton displayButton;
    private javax.swing.JTextArea displayOutput;
    private javax.swing.JComboBox<String> districtComboBox;
    private javax.swing.JRadioButton emailRadioButton;
    private javax.swing.JButton evaluateButton;
    private javax.swing.JLabel fNameError;
    private javax.swing.JTextField firstNameInput;
    private javax.swing.JLabel idError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNameError;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JRadioButton meetingRadioButton;
    private javax.swing.JLabel paperError;
    private javax.swing.JTextField paperInput;
    private javax.swing.JRadioButton phoneRadioButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JTextField salesIdInput;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel successLabel;
    private javax.swing.JLabel suppliesError;
    private javax.swing.JTextField suppliesInput;
    // End of variables declaration//GEN-END:variables
}
